// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    1: typeof import('./components/1.vue')['default']
    2: typeof import('./components/2.vue')['default']
    3: typeof import('./components/3.vue')['default']
    4: typeof import('./components/4.vue')['default']
    ComHeader: typeof import('./components/com/header.vue')['default']
    ComMouse: typeof import('./components/com/mouse.vue')['default']
    Demo: typeof import('./components/demo.vue')['default']
    MySlot: typeof import('./components/MySlot.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NotFound: typeof import('./components/NotFound.vue')['default']
    NSwitch: typeof import('naive-ui')['NSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
